# Utiliser l'image officielle de Tomcat 10
FROM tomcat:10


LABEL maintainer="Mohamed"

# Exemple pour copier votre application WAR dans le répertoire webapps de Tomcat
# COPY votre_application.war /usr/local/tomcat/webapps/
